### ISSUE TITLE
router-bridge: Packaging and distribution approaches

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/federation-rs#123]
This conversation is revisiting the #15 decisions now that the product has evolved.

## Context

The rust router-bridge is currently relying on build.rs to invoke `npm` and generate the required .js files it will invoke at runtime.

This leads to:
- Router developers need to have Nodejs and NPM installed and in their path
- Increased compile time when building the Router

Previously identified options (have a look at the linked issue for more info):
## 1 - Check in the js output:

- generate the js files by running the `npm run compile:for-router-bridge-build-rs` while developing.
- check in the output directory to the repository
  
## 2 - move router-bridge to a separate repository

- move router-bridge to a separate repository
- have router-bridge depend to a specific version of query planner
- regularly update the dependency

## 3 - publish as `apollo-router-bridge` 

Essentially, this will work the same way as `harmonizer` does today, where the actual `.js` is in the published crate.  The `router` would then merely depend on _that_.

New option:

## 4 - pre generate snapshots for each of our target architectures.
Pros:
- we wouldn't need to check in the js-dist
- we could get rid of the whole build-rs (much faster build times)

Cons:
- we need a publish command that generates these
- we need to make sure we can generate the snapshots for each of our supported platforms

## Previous decisions

We did act on option number 2; but we are still suffering the need for our downstream users to have NPM and Nodejs installed.

This becomes more of a pain point now that our users are trying to build their own routers; [they hit this more](https://github.com/apollographql/router/issues/155#issuecomment-1049154477).

Publishing apollo-router-bridge looks like the most sensible approach to me; since it would allow our downstream users to not have to deal with the npm dance; and we would still have a good local development experience.

**Comment by o0Ignition0o** [comment]
@EverlastingBugstopper AIUI Harmonizer is being published, and we now intend to figure out how you did that and apply the same process to the bridge!

**Comment by EverlastingBugstopper** [comment]
let me know if you would like to pair up for a bit! happy to help

**Comment by o0Ignition0o** [comment]
The bridge is [published](https://crates.io/crates/router-bridge)!
