### ISSUE TITLE
A path to upgrade deno on harmonizer (so it can be upgraded workspace wide)

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/federation-rs#124]
the router-bridge is currently stuck relying on `deno-core` version `0.124.0` because there s a dependency conflict with once_cell

```bash
error: failed to select a version for `once_cell`.
    ... required by package `deno_core v0.135.0`
    ... which satisfies dependency `deno_core = "^0.135.0"` of package `router-bridge v0.1.0 (/Users/ignition/projects/apollo/federation-rs/federation-2/router-bridge)`
versions that meet the requirements `^1.10.0` are: 1.12.0, 1.11.0, 1.10.0

all possible versions conflict with previously selected packages.

  previously selected package `once_cell v1.9.0`
    ... which satisfies dependency `once_cell = "=1.9.0"` of package `deno_core v0.118.0`
    ... which satisfies dependency `deno_core = "^0.118.0"` of package `harmonizer v2.0.2 (/Users/ignition/projects/apollo/federation-rs/federation-2/harmonizer)`
    ... which satisfies path dependency `harmonizer` (locked to 2.0.2) of package `supergraph v2.0.2 (/Users/ignition/projects/apollo/federation-rs/federation-2/supergraph)`

failed to select a version for `once_cell` which could resolve this conflict
```

The main issue preventing us from bumping harmonizer is that a lot of things changed between deno-core 0.118.0 and 0.124.0.

Here's a rough list of things that changed, the actual upgrade that happened in the bridge [can be found in this comment](https://github.com/apollographql/federation-rs/commit/a1846dd1780989cbad767249c9c4f59a649523ad)

callback declaration is done through the #[op] macro:
- sync functions are declared [like this](https://github.com/apollographql/federation-rs/blob/a1d71a13416979fda3a62d1dbb4df54379c17801/federation-2/router-bridge/src/worker.rs#L211)
- async functions are declared [like that](https://github.com/apollographql/federation-rs/blob/a1d71a13416979fda3a62d1dbb4df54379c17801/federation-2/router-bridge/src/worker.rs#L217)
- they are hooked in the runtime [like this](https://github.com/apollographql/federation-rs/blob/a1d71a13416979fda3a62d1dbb4df54379c17801/federation-2/router-bridge/src/worker.rs#L58)
- and you can put things in the global state [like that](https://github.com/apollographql/federation-rs/blob/a1d71a13416979fda3a62d1dbb4df54379c17801/federation-2/router-bridge/src/worker.rs#L68)
- Finally here's how you can invoke [sync functions](https://github.com/apollographql/federation-rs/blob/a1d71a13416979fda3a62d1dbb4df54379c17801/federation-2/router-bridge/js-src/runtime.js#L3) and [async functions](https://github.com/apollographql/federation-rs/blob/a1d71a13416979fda3a62d1dbb4df54379c17801/federation-2/router-bridge/js-src/plan_worker.ts#L128) in js / ts land.

A lot of the complexity/machinery in worker.rs is due to our planner being long lived, and passing messages back and forth from / to Rust and the Deno runtime. This probably doesn't need to be ported since the cli is probably short lived overall.

I would highly recommend us to first try to bump Harmonizer to `0.124.0`, before we try to bump both to `0.135.0`.

@EverlastingBugstopper are there some caveats in harmonizer land that we should keep in mind if we wanna tackle this? wdyt? 🤗

**Comment by EverlastingBugstopper** [comment]
No caveats in harmonizer land I think. I love all the runtime stuff you've done for router-bridge here and I wonder how much of it we can pull out - like, can we have an `apollo-deno-core` subcrate or something that is the only thing that depends on deno so that when we update it for harmonizer it gets updated for router-bridge?

**Comment by o0Ignition0o** [comment]
Having an `apollo-deno-core` crate sounds great! I think it would require us to expose two apis:
one for short lived "run the script once" workers
one for long lived "spin a while true loop and listen to commands" workers

While this looks like a sensible approach in the long run, I think the first step would be to bump deno on the harmonizer, so both packages are up to date.

We could then start refactoring (which would take longer)

**Comment by Geal** [comment]
a ping! on this: this is now blocking updates to tracing and tracing-core in the router, as they require incompatible versions: https://github.com/apollographql/router/pull/1002#pullrequestreview-1019878072
and users are noticing the ssue when trying to use `cargo-outdated` https://github.com/apollographql/router/issues/1323

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/cargo/issues/6584#issuecomment-457245362 explains that while Cargo supports having multiple versions of the same grate in a dependency graph, it only choose to do so if they have version numbers considered SemVer-*in*compatible. This constraint is arguably undesirable (as it is here), but that thread says changing it might require a Rust RFC.
