### ISSUE TITLE
router-bridge: consider alternative packaging approaches

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/federation-rs#15]
The rust router-bridge is currently relying on build.rs to invoke `npm run compile:for-router-bridge-build-rs` and generate the required .js files it will invoke at runtime.

Relying on a build.rs step has an impact on downstream build times.
Moreover the build.rs step invokes an npm command, which requires downstream (rust) users to have a nodejs environment available.

Goals:
- We would like to get rid of the build.rs file
- It would be great if we didn't need a nodejs / npm environment to build downstream libraries (the router for example).
- We want to make sure the bridge remains in sync with the underlying js / ts code.

A couple of options:
## 1 - Check in the js output:

- generate the js files by running the `npm run compile:for-router-bridge-build-rs` while developing.
- check in the output directory to the repository
  
### pros: 
  - the build step is gone
  - downstream users won't need to have an npm / node environment at hand (rusty_v8 gets pulled in when running cargo build)
  - the bridge remains in sync (and tests make sure the bridge keeps working)
### cons:
  - these are a lot of files
  - this will introduce noise to any pull request that changes query planning / query introspection

## 2 - move router-bridge to a separate repository

- move router-bridge to a separate repository
- have router-bridge depend to a specific version of query planner
- regularly update the dependency

### pros:
 - the federation team doesn't have to maintain router-bridge anymore
 - one less build step
 ### cons:
 - hard to see when the js code is out of sync
 - hard to track breaking changes in the query-planner

there are probably other ways to deal with it, I'm not really sure which solution would be best, what does the federation team think?

**Comment by abernix** [comment]
@EverlastingBugstopper I think I agree with @o0Ignition0o here!  This is in full thanks to your work.  Any _closing_ thoughts? 

(In reality, this issue on this [new, `federation-rs`] repository is actually the sign that we went with step two above).

**Comment by EverlastingBugstopper** [comment]
publishing concerns still not entirely addressed, though nothing's really changed in that regard, we'll still just publish to crates.io. that's tracked in #13 though so I feel good enough to close this.
