### ISSUE TITLE
Concurrent query planning

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/federation-rs#219]
We should measure and improve the way our query planner scales.

My theory is that due to the CPU bound nature of planning, the two ways to scale the planner would involve either:
- Spawning several deno runtimes
- Using web workers within a deno runtime

I'm tempted to favor the ~former~ latter approach, for memory footprint reasons. But before we try to improve the performance, we need to profile this.

Steps to take:

- [x] write a benchmark that measures query planning timing and how long planning N queries takes using a single deno runtime
- [x] update deno dependencies to be able to use new features
- [ ] implement and measure the perf gains of webworkers

**Comment by garypen** [comment]
> I'm tempted to favor the former approach, for memory footprint reasons. But before we try to improve the performance, we need to profile this.

I think you mean "latter" rather than "former"? i.e.: web workers should use less memory than several runtimes.

**Comment by o0Ignition0o** [comment]
right :D
