### ISSUE TITLE
router-bridge: re-compose the test schema using the core spec v0.2

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/federation-rs#27]
followup to https://github.com/apollographql/federation/pull/1090#discussion_r729707891 the [`testdata/schema.graphql`](https://github.com/apollographql/federation-rs/blob/main/router-bridge/src/testdata/schema.graphql) has been generated a long time ago, and doesn't exercise the newer `core` and `join` specifications.

**Comment by abernix** [comment]
I don't know that this is going to happen, nor that it even needs to, anymore.
