### ISSUE TITLE
router-bridge: add jest tests

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/federation-rs#28]
Followup to a comment posted by @abernix in https://github.com/apollographql/federation/pull/1090#discussion_r729709513_, we need to add jest tests so that breaking changes can be caught by the federation teams, even if they don't run `cargo test`.

**Comment by EverlastingBugstopper** [comment]
things to consider adding tests in the upstream `federation` repo:

- reliance on node std modules
- JSON with cyclical dependencies

**Comment by o0Ignition0o** [comment]
Closing this one because we have a pretty good test harness on the bridge, and it hasnt bitten us in a while.

Let's reopen it if we encounter that again.
