### ISSUE TITLE
router-bridge: move the router-bridge to its own repository

### ISSUE THREAD

**Issue by abernix** [apollographql/federation-rs#31]
... automatically publishing to crates.io when the npm package is bumped and published.

**Comment by o0Ignition0o** [comment]
@EverlastingBugstopper not too sure about this one (got misslead by the issue title)
especially the
> automatically publishing to crates.io when the npm package is bumped and published.

**Comment by EverlastingBugstopper** [comment]
i think we should track that in #13 since there are multiple crates that need this to be figured out and we should have a cohesive strategy for all.
