### ISSUE TITLE
migrate and build `router-bridge`  

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/federation-rs#5]
`router-bridge` should be moved out of `federation` and into this repo, once we figure out how to do it properly for `harmonizer`.

**Comment by o0Ignition0o** [comment]
Almost there, one more fix to go:

[ci on windows is not happy with us running mkdir -p](https://app.circleci.com/pipelines/github/apollographql/router/1437/workflows/4ab88c27-ea39-4c78-942d-54f024ead690/jobs/9696)

**Comment by EverlastingBugstopper** [comment]
this is done
