### ISSUE TITLE
xtask: create artefacts but don't publish them

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/federation-rs#66]
Debugging build issues locally is a bit painful at the moment, because there is no simple way for us to generate a harmonizer package that looks the same as the one we would publish.

This means it was a bit hard for me to find out what was exactly happening in https://github.com/apollographql/rover/pull/1030

a `cargo xtask prepublish` command would come in handy, it would:
- Create a new folder, say `prepublish`
- Copy the sources one would publish over there
- Copy the `Cargo.publish.toml` and rename it to `Cargo.toml`

This means local rover developers would for example be able to target this `prepublish`ed directory and make sure everything is working as expected.

Moreover this would allow us to be more confident that what we publish is exactly what we're seeing.

**Comment by EverlastingBugstopper** [comment]
`cargo xtask prep` does exactly this!
