### ISSUE TITLE
add `composition-latest-0` and `composition-latest-2` tags when running `cargo xtask tag`

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/federation-rs#80]
in orbiter, we need a way to get the latest version of the `supergraph` CLIs for either v0 or v2. easiest way to do this is with a tag that we update for each. i've manually created these tags based on what's here but we need to automate updating it. i've already created the first versions of these tags locally. until this is closed we should manually update them to point to the correct place.

**Comment by EverlastingBugstopper** [comment]
thinking on how this would work in practice - we don't want to update the tags until the tarball and installer endpoints for a new version are live. therefore, i think we should have something maybe like `cargo xtask promote supergraph@v{version}` run _after_ the packages are uploaded to GitHub, which would run the following in [`GitRunner`](https://github.com/apollographql/federation-rs/blob/main/xtask/src/tools/git.rs): 

```
git tag -d composition-latest-2 && git tag -a composition-latest-2 -m v{version} && git push --tags -f
```

**Comment by benweatherman** [comment]
The `cargo xtask promote` flow makes sense, and gives us a chance to test before making it live. I think the jankiness is great for now 😈

**Comment by EverlastingBugstopper** [comment]
this has been superseded by #197 - we should use renovate in the rover repo to handle updating these
